# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-25 22:21
from __future__ import unicode_literals

from django.db import migrations, models
import posts.models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_auto_20160119_1724'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=posts.models.upload_location),
        ),
        migrations.AddField(
            model_name='post',
            name='slug',
            field=models.SlugField(default=2323, unique=True),
            preserve_default=False,
        ),
    ]
