# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-26 19:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0005_post_kategoria'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='kategoria',
            field=models.CharField(choices=[('MI', 'Miesa'), ('GA', 'Garmazeria'), ('AS', 'Artykuly spozywcze'), ('NA', 'Napoje')], default='AS', max_length=2),
        ),
    ]
