# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-27 18:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0006_auto_20160126_1908'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='kategoria',
            field=models.CharField(choices=[('WE', 'Wedliny'), ('GA', 'Garmazeria'), ('AS', 'Artykuly spozywcze'), ('NA', 'Napoje'), ('PO', 'Posty')], default='AS', max_length=2),
        ),
        migrations.AlterField(
            model_name='post',
            name='slug',
            field=models.SlugField(unique=True),
        ),
    ]
